### PR TITLE
fix: check if an URL is provided

### PR DESCRIPTION
**Pull request by DanielRuf**
Relevant: #9

### CODE REVIEW

**Comment by mirkoschubert** [comment]
Sorry, I already fixed it.

**Comment by DanielRuf** [comment]
Ok. But keep in mind that only non-zero exit codes are for errors. 0 meant that everything is ok and other tools which parse the result code would say that it ran successfully.

**Comment by DanielRuf** [comment]
See https://en.wikipedia.org/wiki/Exit_status#Shell_and_scripts

> For the shell’s purposes, a command which exits with a zero exit status has succeeded. A nonzero exit status indicates failure. This seemingly counter-intuitive scheme is used so there is one well-defined way to indicate success and a variety of ways to indicate various failure modes. When a command is terminated by a signal whose number is N, a shell sets the variable $? to a value greater than 128. Most shells use 128+N, while ksh93 uses 256+N.

> If a command is not found, the shell should return a status of 127. If a command is found but is not executable, the return status should be 126.[2] Note that this is not the case for all shells.

> If a command fails because of an error during expansion or redirection, the exit status is greater than zero.

**Comment by mirkoschubert** [comment]
Didn't know that (I'm still learning...) 😄 Changed it.

**Pull request closed without merging**
