### PR TITLE
chore: improve performance of getPrefetchingInformation

### PR DESCRIPTION
**Pull request by DanielRuf**
See #15 

regex should be just used as last solution as regular expressions are internally compiled and consume much more CPU cycles and memory.

And they are hard to optimize for the compiler in general.

https://medium.com/dailyjs/js-regexp-fast-and-slow-d29d6b77b06
https://www.future-processing.pl/blog/javascript-is-slow/
https://docs.microsoft.com/en-us/dotnet/standard/base-types/compilation-and-reuse-in-regular-expressions
https://www.regular-expressions.info/engine.html
https://www.regular-expressions.info/tutorial.html
https://softwareengineering.stackexchange.com/questions/122440/how-do-regular-expressions-actually-work
https://stackoverflow.com/questions/3622398/how-a-regex-engine-works

Important: do not use regex if it works with the native string / number / object / array methods.

### CODE REVIEW

**Comment by mirkoschubert** [comment]
You're absolutely right 😄 But please send pull requests only to the `dev` branch in the future!

**Comment by DanielRuf** [comment]
> You're absolutely right 😄 But please send pull requests only to the dev branch in the future!

Right, can you change the default branch to `dev` for contributors?

**Comment by mirkoschubert** [comment]
@DanielRuf You can do that? Or is it the overall default branch setting?
Sorry, I'm pretty new to this. In fact, this project is my first relating to working with contributors and working with a separate development branch 😆

**Comment by DanielRuf** [comment]
> Or is it the overall default branch setting?

Just this one (for all). But this is what we also do/did at zurb/foundation-sites.

**Pull request merged**
